# Generated by Django 4.1.1 on 2022-09-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0005_alter_shop_reg_address_alter_shop_reg_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_product',
        ),
    ]
