# Generated by Django 4.1.1 on 2022-09-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0006_delete_add_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop_reg',
        ),
    ]
