# Generated by Django 4.1.1 on 2022-10-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0013_alter_add_product_quantity_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='user',
        ),
        migrations.AddField(
            model_name='add_product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructionapp.shop_reg'),
        ),
    ]
