# Generated by Django 4.1.1 on 2022-10-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0014_remove_add_product_user_add_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_reg',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
