# Generated by Django 4.1.1 on 2022-10-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0015_shop_reg_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_reg',
            name='location',
        ),
    ]
