# Generated by Django 4.1.1 on 2022-10-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0016_remove_shop_reg_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='location',
        ),
    ]
