# Generated by Django 4.1.1 on 2022-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0019_feedback_delete_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='action',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
