# Generated by Django 4.1.1 on 2022-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0020_rename_description_feedback_action_feedback_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AlterField(
            model_name='add_product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
