# Generated by Django 4.1.1 on 2022-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0022_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='chat',
        ),
    ]
