# Generated by Django 4.1.1 on 2022-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0024_feedback_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='statuss',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
