# Generated by Django 4.1.1 on 2022-10-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0025_feedback_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructionapp.shop_reg'),
        ),
    ]
