# Generated by Django 4.1.1 on 2022-11-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0027_cart_action_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='statuss',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
