# Generated by Django 4.1.1 on 2022-11-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0028_cart_statuss_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='adminrply',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shoprply',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
