# Generated by Django 4.1.1 on 2022-11-19 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0029_cart_adminrply_cart_shoprply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='action',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='adminrply',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shoprply',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='statuss',
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructionapp.add_product'),
        ),
    ]
